

define( [
	"dojo/_base/declare",
	"dojo",
	"dojo/dojo",
	"dojo/i18n",
	"dojo/ready",
	"dojox",
	"dojox/main",
	"dojo/request",
	"dojo/request/xhr",
  "dijit/dijit",
  "dojo/parser",
  "dojo/selector/acme",
  "dojo/_base/connect",
  "dijit/TitlePane",
  "dijit/Toolbar",
  "dijit/form/Button",
  "dojox/form/CheckedMultiSelect",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "dojox/data/CsvStore",
  "dijit/MenuBar",
  "dijit/PopupMenuBarItem",
  "dijit/MenuItem",
  "dijit/Menu",
  "dojo/fx/Toggler",
  "dijit/ToolbarSeparator",
  "dijit/CheckedMenuItem",
  "dijit/MenuSeparator",
  "dijit/form/RadioButton",
  "dijit/form/_RadioButtonMixin",
  "dijit/TooltipDialog",
  "dijit/form/SimpleTextarea",
  "dijit/form/TextBox",
  "dijit/form/CheckBox",
  "dijit/layout/TabContainer",
  "dijit/layout/ContentPane",
  "dojox/mobile",
//  "dojox/mobile/deviceTheme",
	"dojox/mobile/Heading",
  "dojox/mobile/_EditableListMixin",
  "dojox/mobile/_compat",
//  "dojox/mobile/compat",
  "dojo/hash",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "dojox/mobile/RoundRectDataList",
  "dijit/form/DataList",
  "dojox/mobile/ComboBox",
  "dojox/mobile/ToolBarButton",
  "dijit/layout/ContentPane",
  "dijit/form/Form",
  "dojox/mobile/TextBox",
  "dojox/mobile/Button",
  "dojox/mobile/RoundRectCategory",
  "dojox/widget/Standby",
  "dojox/mobile/TabBar",
  "dojox/mobile/TabBarButton",
  "dojox/mobile/RoundRectDataList",
  "dojox/mobile/RoundRectList",
	"dojox/mobile/TextBox",
	"dojox/mobile/CheckBox",
	"dojox/mobile/ScrollableView",
  "dojox/mobile/TabBar",
  "dijit/Dialog",
  "dojox/widget/Standby",
  "dijit/form/MultiSelect"

	], function() {}
);





